import type { Phrase, SrsRecord } from "@/types";
import { todayKey, daysBetween } from "./date";
import { isDue } from "./srs";

/**
 * A seed set of high-frequency, genuinely native phrases/idioms — the kind
 * people actually say. Each carries 2+ "similar ways" (popular alternatives) so
 * the learner learns a flexible *cluster*, not one brittle phrase.
 *
 * (Later these also come from trending content and from phrases mined from the
 * learner's own writing; alternatives for those can be generated by AI.)
 */
export const SEED_PHRASES: Phrase[] = [
  {
    id: "ph-ice", text: "break the ice", meaning: "start a conversation in an awkward or new situation",
    example: "I told a joke to break the ice with the new team.", register: "casual",
    alternatives: [{ text: "get the conversation going" }, { text: "warm things up" }, { text: "get the ball rolling", note: "also = get something started" }],
  },
  {
    id: "ph-page", text: "on the same page", meaning: "in agreement / sharing the same understanding",
    example: "Let's have a quick call so we're all on the same page.", register: "at work",
    alternatives: [{ text: "on the same wavelength" }, { text: "see eye to eye", note: "= agree" }],
  },
  {
    id: "ph-cake", text: "a piece of cake", meaning: "very easy",
    example: "The exam was a piece of cake — I finished early.", register: "casual",
    alternatives: [{ text: "no sweat" }, { text: "easy as pie" }, { text: "a walk in the park" }],
  },
  {
    id: "ph-day", text: "call it a day", meaning: "decide to stop working for now",
    example: "We've done enough — let's call it a day.", register: "casual",
    alternatives: [{ text: "wrap it up" }, { text: "knock off for the day" }],
  },
  {
    id: "ph-bell", text: "ring a bell", meaning: "sound familiar",
    example: "That name rings a bell, but I can't place her.", register: "casual",
    alternatives: [{ text: "sound familiar" }, { text: "that reminds me of something" }],
  },
  {
    id: "ph-chase", text: "cut to the chase", meaning: "get to the point without wasting time",
    example: "I'll cut to the chase: we need this by Friday.", register: "at work",
    alternatives: [{ text: "get to the point" }, { text: "long story short" }],
  },
  {
    id: "ph-court", text: "the ball is in your court", meaning: "it's your turn to decide or act",
    example: "I've sent my offer — now the ball is in your court.", register: "neutral",
    alternatives: [{ text: "it's your call" }, { text: "it's up to you" }],
  },
  {
    id: "ph-bullet", text: "bite the bullet", meaning: "force yourself to do something difficult you've been avoiding",
    example: "I finally bit the bullet and booked the dentist.", register: "casual",
    origin: "From soldiers biting a bullet to bear pain before anesthetic.",
    alternatives: [{ text: "just get it over with" }, { text: "grit your teeth and do it" }, { text: "take the plunge", note: "esp. a big step" }],
  },
  {
    id: "ph-hang", text: "hang in there", meaning: "stay strong; don't give up",
    example: "I know it's hard — hang in there, it gets better.", register: "casual",
    alternatives: [{ text: "stay strong" }, { text: "don't give up" }, { text: "stick with it" }],
  },
  {
    id: "ph-weather", text: "under the weather", meaning: "feeling a little ill",
    example: "I'm a bit under the weather, so I'll rest today.", register: "casual",
    alternatives: [{ text: "feeling off" }, { text: "not 100%" }, { text: "a bit run down" }],
  },
  {
    id: "ph-sack", text: "hit the sack", meaning: "go to bed",
    example: "I'm exhausted — I'm going to hit the sack.", register: "casual",
    alternatives: [{ text: "turn in" }, { text: "hit the hay" }, { text: "call it a night" }],
  },
  {
    id: "ph-beans", text: "spill the beans", meaning: "reveal a secret",
    example: "Come on, spill the beans — what did she say?", register: "casual",
    origin: "Possibly from ancient voting with beans that could be spilled early.",
    alternatives: [{ text: "let the cat out of the bag" }, { text: "give it away" }],
  },
];

export function phraseById(id: string): Phrase | undefined {
  return SEED_PHRASES.find((p) => p.id === id);
}

/**
 * How many phrases are queued for practice today, capped at the daily session
 * size — the number the Phrase Coach badge nudges with. New phrases count as
 * due; returns 0 (badge hidden) once today's rotation is cleared.
 */
export function dueTodayCount(
  srs: Record<string, SrsRecord>,
  extra: Phrase[] = [],
  cap = 3,
): number {
  const today = todayKey();
  const all = [...SEED_PHRASES, ...extra];
  const due = all.reduce((n, p) => (isDue(srs[p.id], today) ? n + 1 : n), 0);
  return Math.min(due, cap);
}

/**
 * "Today's phrases": the ones due for practice (new + review-due), newest first,
 * then soonest due. Deterministic per day so the session is stable on reload.
 * `extra` folds in phrases mined from other modes (e.g. News Chat) so they enter
 * the same spaced-repetition rotation as the seed set.
 */
export function todaysPhrases(
  srs: Record<string, SrsRecord>,
  extra: Phrase[] = [],
  count = 3,
): Phrase[] {
  const today = todayKey();
  const all = [...SEED_PHRASES, ...extra];
  const due = all.filter((p) => isDue(srs[p.id], today));
  const pool = due.length > 0 ? due : all;
  const sorted = [...pool].sort((a, b) => {
    const ra = srs[a.id];
    const rb = srs[b.id];
    const newA = ra ? 1 : 0;
    const newB = rb ? 1 : 0;
    if (newA !== newB) return newA - newB; // brand-new phrases first
    const dueA = ra ? daysBetween(today, ra.due) : 0;
    const dueB = rb ? daysBetween(today, rb.due) : 0;
    return dueA - dueB; // then most-overdue first
  });
  return sorted.slice(0, count);
}
